### ISSUE TITLE
1.7.10 don't work!

### ISSUE THREAD

**Issue by GilloDaby** [LMBishop/Quests#100]
**Description of Error**
(1) Inventory bug after quest started
(2) The plugin work but after you  start a quest the plugin bug and cannot be use!
**To Reproduce**
(First bug) Need start a quest in 1.7.10 after if you go in creative mods you can not pick any objet.
(Second bug) You can not go back in the categories of the quest you just started after. 
**Screenshots**
[if you have any screenshots, show them here]
https://i.imgur.com/qMJoTUp.png
**Server (please complete the following information):**
 - Minecraft Version: [e.g. 1.7.10]
 - Mod Name: [e.g. Spigot]

**Plugin (please complete the following information):**
 - Version: [e.g. 2.5 but I try every version of plug and doesn't work]

**Stacktrace**
> [18:19:48 ERROR]: [Minecraft] Could not pass event InventoryClickEvent to Quests v2.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:288) ~[server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [server.jar:git-PaperSpigot-ea452ce]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1460) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:190) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:787) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:306) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:635) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:541) [server.jar:git-PaperSpigot-ea452ce]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-ea452ce]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
at com.leonardobishop.quests.obj.misc.QItemStack.toItemStack(QItemStack.java:85) ~[?:?]
at com.leonardobishop.quests.obj.misc.QMenuQuest.toInventory(QMenuQuest.java:136) ~[?:?]
at com.leonardobishop.quests.player.QPlayer.openCategory(QPlayer.java:88) ~[?:?]
at com.leonardobishop.quests.events.EventInventory.onEvent(EventInventory.java:98) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:284) ~[server.jar:git-PaperSpigot-ea452ce]
... 13 more

**Comment by alfiejsmith** [comment]
not sure why you're expecting support for 1.7.10 on a 1.15.2 plugin

**Comment by GilloDaby** [comment]
Why on the compatibility list is mark as compatible in 1.7.10 ? 
https://i.imgur.com/Kwz5SR7.png

**Comment by alfiejsmith** [comment]
See where it says "The plugin is very likely to work but not confirmed"

**Comment by GilloDaby** [comment]
Damn I read the bad line so you can change this (1.7.x to NO)

And sorry have a good day
