### ISSUE TITLE
PAPI breaks plugin on every version after v3.9

### ISSUE THREAD

**Issue by SkyHazeSB** [LMBishop/Quests#324]
### Description of Bug

When enabling PAPI in any version after v3.9 and you have placeholders in the category descriptions, the plugin fails to load the quests gui and gives an internal error. I downgraded to version 3.9 and everything works as expected.

### Steps to Reproduce

Have a place holder in any category's description and be on a version after v3.9, enable placeholder-api in config, then do /quests.

### Environment

- Minecraft version: 1.12.2
- Server software: Spigot 1.12.2
- Quests version: v3.9.1, v3.9.2, v3.10

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Can you paste the error?

**Comment by SkyHazeSB** [comment]
Of course! 

[15:30:58] [User Authenticator #1/INFO]: UUID of player alnoise is 64c10e24-add1-4d68-9af1-076362e2ff8a
[15:30:59] [Server thread/INFO]: is leader = false
[15:30:59] [Server thread/INFO]: alnoise[/127.0.0.1:58897] logged in with entity id 205 at ([ASkyBlock]323.53243600287834, 120.0, 274.46545139235303)
[15:30:59] [Server thread/INFO]: [ASkyBlock] No update available.
[15:31:01] [Craft Scheduler Thread - 8/INFO]: [0;36;1m[21m(!) [0;36;1mIslandTop [0;37;22mWe are now calculating all islands ![m
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:02] [Server thread/WARN]: Skipping BlockEntity with id 
[15:31:03] [Server thread/INFO]: alnoise issued server command: /quests
[15:31:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.10
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_321]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.NullPointerException
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:44) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.11.1.jar:?]
	at com.leonardobishop.quests.bukkit.hook.papi.PlaceholderAPIHook.replacePlaceholders(PlaceholderAPIHook.java:12) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.lambda$onEnable$2(BukkitQuestsPlugin.java:253) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.util.MenuUtils.applyPlaceholders(MenuUtils.java:44) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.util.MenuUtils.applyPlaceholders(MenuUtils.java:20) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.menu.element.CustomMenuElement.<init>(CustomMenuElement.java:14) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.menu.CategoryQMenu.populate(CategoryQMenu.java:54) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.menu.MenuController.openMainMenu(MenuController.java:136) ~[Quests-3.10.jar:?]
	at com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:63) ~[Quests-3.10.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-79a30d7-f4830a1]
	... 15 more
[15:31:03] [Server thread/INFO]: [0;36;1m[21m(!) [0;36;1mIslandTop [0;37;22mCalculation has finished ![m

Here’s a hastebin link if that makes it easier,
https://www.toptal.com/developers/hastebin/eqosihafed.sql
