### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Mick43** [LMBishop/Quests#38]
Version 2.0.15

[Craft Scheduler Thread - 101/WARN]: [Quests] Plugin Quests v2.0.15 generated an exception while executing task 143166
java.lang.NullPointerException: null
	at com.leonardobishop.quests.events.EventPlayerLeave$1.run(EventPlayerLeave.java:19) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.2.jar:git-Spigot-e4d0c66-aed3aec]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-e4d0c66-aed3aec]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by lmbishop** [comment]
Can you try and find an error when the player joins? That one would be useful.
