### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by sandor111** [LMBishop/Quests#39]
`[21:53:43] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.0.15
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-TacoSpigot-"95870a93"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException`

**Comment by sandor111** [comment]
Another one:
`[12:51:49] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Quests v2.0.15
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paper.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:160) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-TacoSpigot-"95870a93"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException`

**Comment by sandor111** [comment]
More
`[18:28:45] [Server thread/WARN]: [Quests] Task #746 for Quests v2.0.15 generated an exception
java.lang.NullPointerException
	at com.leonardobishop.quests.quests.tasktypes.types.PlaytimeTaskType$1.run(PlaytimeTaskType.java:28) ~[quests%20(3).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [paper.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by lmbishop** [comment]
I’m specifically looking for an error from the PlayerJoinEvent. Can you find one in your logs?

**Comment by sandor111** [comment]
> I’m specifically looking for an error from the PlayerJoinEvent. Can you find one in your logs?

Nope, can't find any.

Only these:
[20:18:40] [Server thread/ERROR]: Could not pass event PlayerFishEvent to Quests v2.0.15
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.ItemFishingRod.a(ItemFishingRod.java:23) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:237) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:371) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:719) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-TacoSpigot-bf023c7d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [paper.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldError: BITE
	at com.leonardobishop.quests.quests.tasktypes.types.FishingTaskType.onFishCaught(FishingTaskType.java:36) ~[quests%20(3).jar:?]
	at sun.reflect.GeneratedMethodAccessor1265.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[paper.jar:git-TacoSpigot-bf023c7d]
	... 19 more``

`[01:26:26] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Quests v2.0.15
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [paper.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:133) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:161) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:748) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-TacoSpigot-bf023c7d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [paper.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [paper.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at com.leonardobishop.quests.quests.tasktypes.types.BuildingCertainTaskType.onBlockPlace(BuildingCertainTaskType.java:43) ~[quests%20(3).jar:?]
	at sun.reflect.GeneratedMethodAccessor313.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[paper.jar:git-TacoSpigot-bf023c7d]
	... 19 more`

**Comment by lmbishop** [comment]
Have you or any staff used the mod data command recently?

**Comment by sandor111** [comment]
I am pretty sure that no one has used that command.
