### ISSUE TITLE
Console error (ShopGUIPlus)

### ISSUE THREAD

**Issue by Stick3rz** [LMBishop/Quests#438]
### Description of Bug

Hi whenever a player sells or purchases an item via ShopGUIPlus the error below occurs. Any ideas?

- [Sun 13:06:44 ERROR Minecraft] Could not pass event ShopPostTransactionEvent to Quests v3.13.1-77ab390
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
	at Quests-3.13.1-77ab390.jar//com.leonardobishop.quests.bukkit.tasktype.type.dependent.ShopGUIPlusSellTaskType.afterTransaction(ShopGUIPlusSellTaskType.java:49)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1050.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
	at ShopGUIPlus-1.78.0.jar//net.brcdev.shopgui.shop.ShopManager.handleItemSellAll(ShopManager.java:1212)
	at ShopGUIPlus-1.78.0.jar//net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:427)
	at ShopGUIPlus-1.78.0.jar//net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:141)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor893.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3254)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23)
	at net.minecraft.network.protocol.PacketUtils.lamb

### Steps to Reproduce

Sell or purchase via ShopGUIPlus 

### Environment

- Minecraft version: 1.19.1
- Server software: Paper 1.19.1
- Quests version: Latest release.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
This has been resolved in #429
