### ISSUE TITLE
Shopgui event

### ISSUE THREAD

**Issue by nikiasek** [LMBishop/Quests#441]
### Description of Bug

Quests cant pass event shopposttransactionevent

### Steps to Reproduce

I just went to console and i saw this error. i tried to find something on internet but i didnt find anything
---------------------------------------------------------------------------------------------------------------------------------------------
[15:06:56 INFO]: DeadKubina issued server command: /shop
[15:07:02 INFO]: [ShopGUIPlus] DeadKubina bought 1 x Light Gray Shulker Box for 1,000$ from blocks16 shop
[15:07:02 ERROR]: Could not pass event ShopPostTransactionEvent to Quests v3.13.1-23881cf
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.item.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.ShopGUIPlusBuyTaskType.afterTransaction(ShopGUIPlusBuyTaskType.java:49) ~[Quests-3.13.1-23881cf.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor789.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemBuy(ShopManager.java:953) ~[ShopGUIPlus-1.77.4.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:396) ~[ShopGUIPlus-1.77.4.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:139) ~[ShopGUIPlus-1.77.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3053) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Environment

- Minecraft version: 1.19
- Server software:
- Quests version: v3.13.1-23881cf

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by LMBishop** [comment]
Duplicate of #429
