### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Strahilchu** [LMBishop/Quests#453]
### Description of Bug

[11:30:59 ERROR]: Could not pass event ShopPostTransactionEvent to Quests v3.13.2-d709ab4
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.item.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.ShopGUIPlusBuyTaskType.afterTransaction(ShopGUIPlusBuyTaskType.java:49) ~[Quests-3.13.2-d709ab4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1248.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:git-petal-"eb64b15"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemBuy(ShopManager.java:956) ~[ShopGUIPlus-1.77.3.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:396) ~[ShopGUIPlus-1.77.3.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:139) ~[ShopGUIPlus-1.77.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor731.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:git-petal-"eb64b15"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3408) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1335) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1223) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.2.jar:git-petal-"eb64b15"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to Reproduce

Have ShopGui+ Installed, I showed their dev and they said it's Quests fault. I don't want to end up in a back and forth, whos plugin is causing this?

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
update shopgui to the latest version

**Comment by Strahilchu** [comment]
oh wow I really thought I had latest ver, good catch! lol
