### ISSUE TITLE
Could not pass event UserBalanceUpdateEvent to Quests v3.13.2-d709ab4

### ISSUE THREAD

**Issue by iSammyap** [LMBishop/Quests#457]
### Description of Bug

I have this error

java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.math.BigDecimal (java.lang.Double and java.math.BigDecimal are in module java.base of loader 'bootstrap')
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.EssentialsMoneyEarnTaskType.onMoneyEarn(EssentialsMoneyEarnTaskType.java:47) ~[Quests-3.13.2-d709ab4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1324.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1762]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.User.setMoney(User.java:605) ~[EssentialsX-2.19.6.jar:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:249) ~[EssentialsX-2.19.6.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:322) ~[EssentialsX-2.19.6.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:306) ~[EssentialsX-2.19.6.jar:?]
        at com.earth2me.essentials.economy.vault.VaultEconomyProvider.depositPlayer(VaultEconomyProvider.java:255) ~[EssentialsX-2.19.6.jar:?]
        at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:33) ~[Jobs5.1.0.1.jar:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentTask.lambda$run$0(BufferedPaymentTask.java:44) ~[Jobs5.1.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to Reproduce

Only spams the console

### Environment

- Minecraft version: 1.19.2
- Server software: Purpur
- Quests version: 3.13.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

i use the lastest version of EssentialsX stable

**Comment by arlethox** [comment]
same

**Comment by LMBishop** [comment]
What Essentials versions are you using?

**Comment by HEMO313** [comment]
> What Essentials versions are you using?

2.19.7
