### ISSUE TITLE
Could not pass event PlayerMoveEvent to Quests v2.1.2

### ISSUE THREAD

**Issue by MathieuB59** [LMBishop/Quests#47]
spigot version: 1.8.8

[15:31:08] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.1.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Skyblock.jar:git-TacoSpigot-"95870a93"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Skyblock.jar:git-TacoSpigot-"95870a93"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Skyblock.jar:git-TacoSpigot-"95870a93"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [Skyblock.jar:git-TacoSpigot-"95870a93"]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException

**Comment by LMBishop** [comment]
Please try the latest version.
