### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by OnLyMaGiK** [LMBishop/Quests#488]
### Description of Bug

[21:57:23 INFO]: Orsted3173 issued server command: /sellall inventory
[21:57:23 ERROR]: Could not pass event UserBalanceUpdateEvent to Quests v3.13.2-d709ab4
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.math.BigDecimal (java.lang.Double and java.math.BigDecimal are in module java.base of loader 'bootstrap')
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.EssentialsMoneyEarnTaskType.onMoneyEarn(EssentialsMoneyEarnTaskType.java:47) ~[Quests-3.13.2-d709ab4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1103.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.User.setMoney(User.java:605) ~[EssentialsX-2.19.7.jar:?]
        at com.earth2me.essentials.api.Economy.setMoney(Economy.java:249) ~[EssentialsX-2.19.7.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:322) ~[EssentialsX-2.19.7.jar:?]
        at com.earth2me.essentials.api.Economy.add(Economy.java:306) ~[EssentialsX-2.19.7.jar:?]
        at com.earth2me.essentials.economy.vault.VaultEconomyProvider.depositPlayer(VaultEconomyProvider.java:255) ~[EssentialsX-2.19.7.jar:?]
        at me.gypopo.economyshopgui.providers.economys.VaultEconomy.depositBalance(VaultEconomy.java:39) ~[EconomyShopGUI-5.0.1.jar:?]
        at me.gypopo.economyshopgui.commands.Sellall.sellInventory(Sellall.java:157) ~[EconomyShopGUI-5.0.1.jar:?]
        at me.gypopo.economyshopgui.commands.Sellall.execute(Sellall.java:73) ~[EconomyShopGUI-5.0.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-307]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to Reproduce

When a player sells with a decimal, an error appears and the quest is not validated

### Environment

- Minecraft version: 1.19.2
- Server software: Paper
- Quests version: 3.13.2

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by OnLyMaGiK** [comment]
Good morning,
the error occurs after taking the quest and when the player disconnects it, the error is with each movement of his money
