### ISSUE TITLE
Spam  Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by MrMorganCz** [LMBishop/Quests#51]
Hello, I have a new version of quest plugin .. and this is spammed in my console

Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:02 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:40:03 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null

[Quests] Task #386 for Quests v2.6 generated an exception
java.lang.NullPointerException: null
at com.leonardobishop.quests.quests.tasktypes.types.PlaytimeTaskType$1.run(PlaytimeTaskType.java:29) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-210]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
at com.leonardobishop.quests.quests.tasktypes.types.PositionTaskType.onMove(PositionTaskType.java:50) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1035.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1103) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-210]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

uld not pass event EntityDeathEvent to Quests v2.6
java.lang.NullPointerException: null
at com.leonardobishop.quests.quests.tasktypes.types.MobkillingCertainTaskType.onMobKill(MobkillingCertainTaskType.java:55) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1026.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:750) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1419) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1047) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1686) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2031) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088) ~[patched_1.14.4.jar:git-Paper-210]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-210]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[16:57:42 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:57:42 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:57:42 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null
[16:57:42 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6

This server is running Paper version git-Paper-210 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by LMBishop** [comment]
Does this always happen on every restart? Has the plugin generated a data folder and are there any files in it?

**Comment by 6u5t4v** [comment]
I am also getting this error
