### ISSUE TITLE
MySQL connection problem

### ISSUE THREAD

**Issue by Simul4kruM** [LMBishop/Quests#516]
### Description of Bug

Hey...
I'm trying to set up MySQL. I am using https://github.com/LMBishop/Quests/wiki/Storage-Providers#network to do that.

When I upload the config with the changes and restart my server, it completely freezes by booting. The only thing that I see is, that there have been 3 tables created: quests_database_information, quests_quest_progress and quests_task_progress. They are all blank.

The last thing I see in server log is:
[10:35:17] [Server thread/INFO]: [Quests] Enabling Quests v3.13.3-5a28efa
[10:35:17] [Server thread/INFO]: [Quests] Initialising storage provider 'mysql'

No crash, no warning, nothing...

### Steps to Reproduce

- Install Quests-Plugin
- Start Server
- Stop Server
- Edit config and enter database, root, pw and host, changing storage provider to mysql
- Start Server

### Environment

- Minecraft version: 1.19.4
- Server software: Paper 1.19.4
- Quests version: 3.13.3-5a28efa

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

I also tried to migrate my existing quests-yaml-installation to mysql. I created the migration-file, set ready to true, after I entered my sql-stuff into config.yml. By typing the command quests admin migratedata execute in the console, I get the following error:

[11:17:00 INFO]: Performing migration...
[11:17:00 INFO]: Initialising storage provider 'yaml'...
[11:17:00 INFO]: Initialising storage provider 'mysql'...
[11:17:01 INFO]: An error occurred while initializing 'mysql' storage provider. See server console for more details.
[11:17:01 WARN]: com.leonardobishop.quests.libs.hikaricp.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.HikariPool.checkFailFast(HikariPool.java:582)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.HikariPool.<init>(HikariPool.java:115)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.HikariDataSource.<init>(HikariDataSource.java:81)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.bukkit.storage.MySqlStorageProvider.init(MySqlStorageProvider.java:116)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.bukkit.command.AdminMigrateCommandHandler.initProvider(AdminMigrateCommandHandler.java:137)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.bukkit.command.AdminMigrateCommandHandler.lambda$handle$0(AdminMigrateCommandHandler.java:84)
[11:17:01 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:17:01 WARN]: at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:17:01 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:17:01 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:17:01 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:17:01 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[11:17:01 WARN]: Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[11:17:01 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[11:17:01 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[11:17:01 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
[11:17:01 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
[11:17:01 WARN]: at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
[11:17:01 WARN]: at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.PoolBase.newConnection(PoolBase.java:364)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[11:17:01 WARN]: at Quests-3.13.3-5a28efa.jar//com.leonardobishop.quests.libs.hikaricp.pool.HikariPool.checkFailFast(HikariPool.java:561)
[11:17:01 WARN]: ... 11 more
[11:17:01 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[11:17:01 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by Simul4kruM** [comment]
I now achieved to start the migrate process, but it is also stuck by initializing mysql:

[20:15:38 INFO]: Performing migration...
[20:15:39 INFO]: Initialising storage provider 'yaml'...
[20:15:39 INFO]: Initialising storage provider 'mysql'...

What setting could cause this? I mean, the tables have been created, so there is no connection issue... I waited for about 30 mins and the tables have not been filled, even there was no further information in the console...

**Comment by Krakenied** [comment]
Make sure your database and the server's firewall aren't misconfigured

**Comment by Simul4kruM** [comment]
Running about 10 other plugins on same database/server with no problems...

**Comment by Simul4kruM** [comment]
The MySQL-Version is 5.6.33-0ubuntu0.14.04.1. That was the problem with another plugin.

The DEV of it then wrote:
Ok, did some changes to connection proprieties, it looks like that was the main issue when connecting to older MySQL server versions. I was using some connection optimizations with caching and older database servers did not had those.

**Comment by LMBishop** [comment]
Consider upgrading your MySQL version, 5.6.33 was released in August of 2016

**Comment by Simul4kruM** [comment]
I'm not able to update it...
It is a hosted server and I can't change mysql-version.
Is there a way to make the connection work with older versions?

**Comment by Simul4kruM** [comment]
So there is no chance to make it work with older mysql-versions I guess... Do I have to feel forced to look for something else? I am not able to upgrade it...

**Comment by Krakenied** [comment]
You can always use it with yaml storage

**Comment by Simul4kruM** [comment]
That's a bad idea on a bungeecord network...

**Comment by Krakenied** [comment]
It's not a bad idea in a BungeeCord network. You should use MySQL only in case you want to synchronize Quests data between two (or more) backend servers

**Comment by Simul4kruM** [comment]
I got PVE and PVP separated. That's the reason I got to sync data, else I could not do any PVP quests... 
Well, badluck, I created 1080 quests so far. =(

**Comment by Krakenied** [comment]
I will look into it soon

**Comment by Simul4kruM** [comment]
I'm really sorry, but I can't wait anymore, got to find another plugin for our public server then... =( 
You may close this issue, even if it is still unsolved.

Happy new year to you all...

**Comment by Krakenied** [comment]
Unable to reproduce

<img width="956" height="557" alt="Image" src="https://github.com/user-attachments/assets/bfe084b4-4001-4ed5-aca8-48bf60cbf803" />
