### ISSUE TITLE
Commands do not work in-game on MC 1.20.1

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [LMBishop/Quests#554]
### Description of Bug

Plugin is green on /plugins but cannot use commands in-game and when I try to do "quests random" in console it gives this error:
```
quests random
[02:32:03 WARN]: Unexpected exception while parsing console command "quests random"
org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v3.14.2-3345d07
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:970) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @5ce65a89)
        at com.leonardobishop.quests.bukkit.command.RandomCommandHandler.handle(RandomCommandHandler.java:28) ~[Quests-3.14.2-3345d07.jar:?]
        at com.leonardobishop.quests.bukkit.command.CommandSwitcher.handle(CommandSwitcher.java:25) ~[Quests-3.14.2-3345d07.jar:?]
        at com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:69) ~[Quests-3.14.2-3345d07.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

### Steps to Reproduce

Run quests on a 1.20.1 paper server.

config.yml
https://pastebin.com/Ue7B9fwX

### Environment

- Minecraft version:
/ver:
```
[01:51:38 INFO]: This server is running Paper version git-Paper-172 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 72e87ab)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-399 (MC: 1.17.1)
```

- Server software:
/plugins:
```
[01:53:03 INFO]: Server Plugins (41):
[01:53:03 INFO]: Bukkit Plugins:
[01:53:03 INFO]:  - AutomaticInventory, *BeaconEffects, BlockLocker, BossShopPro, CMI, CMILib, CommandPanels, CraftingStore, CrateReloaded, DiscordSRV
[01:53:03 INFO]:  ezAuctions, FastAsyncWorldEdit, FastChunkPregenerator, IllegalStack, InfiniteJump, Kingdoms, LibsDisguises, LuckPerms, mcMMO, MMOItems
[01:53:03 INFO]:  MobFarmManager, Multiverse-Core, MyCommand, MythicLib, MythicMobs, PlaceholderAPI, PlayerParticles, PremiumVanish, ProtocolLib, Quests
[01:53:03 INFO]:  QuickShop, ResourceWorld, SafariNet, ShopGUIPlus, SignShop, Vault, VoidChest, Votifier, VotingPlugin, WorldGuard
[01:53:03 INFO]:  *XRayDetector
```

- Quests version:
Quests-3.14.2-3345d07

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
The q random command must be used by a player

**Comment by LMBishop** [comment]
> Plugin is green on /plugins but cannot use commands in-game and when I try to do "quests random" in console it gives this error

Does the command work in-game?

**Comment by PiggiesGoSqueal** [comment]
> The q random command must be used by a player


> > Plugin is green on /plugins but cannot use commands in-game and when I try to do "quests random" in console it gives this error
> 
> Does the command work in-game?

It does not. It states Unknown Command. Console shows no errors when the commands are attempted:
[01:45:22 INFO]: PiggiesGoSqueal issued server command: /q random
[01:45:26 INFO]: PiggiesGoSqueal issued server command: /quests random
[01:45:28 INFO]: PiggiesGoSqueal issued server command: /quest random

**Comment by PiggiesGoSqueal** [comment]
To update I tried to delete all my configs and let the files regenerate but I still cannot do any quest commands in-game.

**Comment by PiggiesGoSqueal** [comment]
Well, since no reply I'm just going to go ahead and stop using the plugin but just be aware it of my msg before this one. It continues to occur even with fresh files.

**Comment by PiggiesGoSqueal** [comment]
I figured it out. My perms from my last server had disabled the manual use of the quests command for default luckperms group. Apparently even on owner rank(?) with all perms I could not access it. Or perhaps I was testing on a normal player acc at the time idk.
