### ISSUE TITLE
Command in "config.yml" item does not work

### ISSUE THREAD

**Issue by imrexist** [LMBishop/Quests#555]
### Description of Bug

When I add the string commands in the custom-gui it does not work, it throws an error in the console and in the game it does nothing.

```
[00:44:58 ERROR]: Could not pass event InventoryClickEvent to Quests v3.14.2-3345d07
org.bukkit.command.CommandException: Unhandled exception executing command 'q' in plugin Quests v3.14.2-3345d07
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-188]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.leonardobishop.quests.bukkit.menu.element.CustomMenuElement.handleClick(CustomMenuElement.java:39) ~[Quests-3.14.2-3345d07.jar:?]
        at com.leonardobishop.quests.bukkit.menu.MenuController.onClick(MenuController.java:64) ~[Quests-3.14.2-3345d07.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-188]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-188]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-188]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3258) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-188]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @78e03bb5)
        at com.leonardobishop.quests.bukkit.command.StartedCommandHandler.handle(StartedCommandHandler.java:24) ~[Quests-3.14.2-3345d07.jar:?]
        at com.leonardobishop.quests.bukkit.command.CommandSwitcher.handle(CommandSwitcher.java:25) ~[Quests-3.14.2-3345d07.jar:?]
        at com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:69) ~[Quests-3.14.2-3345d07.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 28 more
```

### Steps to Reproduce

Use the plugin in version "Paper 1.20.1" and add a command to an item.

### Environment

- Minecraft version:
```
[00:45:30 INFO]: Checking version, please wait...
[00:45:30 INFO]: This server is running Paper version git-Paper-188 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 06a741d)
You are running the latest version
Previous version: git-Paper-169 (MC: 1.20.1)
```
- Quests version:
```
[00:45:52 INFO]: Quests version 3.14.2-3345d07
[00:45:52 INFO]: Website: https://github.com/LMBishop/Quests
[00:45:52 INFO]: Author: LMBishop & contributors
```

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Config:

```
    15:
      display:
        name: "Test"
        lore:
          - ""
          - "test"
        type: "CHEST_MINECART"
      commands:
          - "q started"
```

**Comment by Krakenied** [comment]
commands in the section are executed by console

**Comment by Krakenied** [comment]
use the following solution:
```
    15:
      display:
        name: "Test"
        lore:
          - ""
          - "test"
        type: "CHEST_MINECART"
      commands:
          - "q a opengui started {player}"

**Comment by imrexist** [comment]
> use the following solution:
> 
> ```
>     15:
>       display:
>         name: "Test"
>         lore:
>           - ""
>           - "test"
>         type: "CHEST_MINECART"
>       commands:
>           - "q a opengui started {player}"
> ```

ty
