### ISSUE TITLE
1.8 is not supported

### ISSUE THREAD

**Issue by ArifErdoganK** [LMBishop/Quests#637]
### Description of Bug

`[01:01:33] [INFO]: [Quests] Enabling Quests v3.15-b636bef
[01:01:33] [INFO]: [Quests] Running server scheduler: BukkitServerSchedulerAdapter
[01:01:33] [INFO]: [Quests] Initialising storage provider 'mysql'
[01:01:33] [INFO]: [Quests] Automatically upgrading database schema from version 1 to 2
[01:01:33] [INFO]: [Quests] Your server is running version 1.8
[01:01:33] [ERROR]: Error occurred while enabling Quests v3.15-b636bef (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/boss/BarColor
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:679) ~[?:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:510) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:435) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:403) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:734) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.boss.BarColor
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[01:01:33] [INFO]: [Quests] Disabling Quests v3.15-b636bef
[01:01:33] [ERROR]: Error occurred while disabling Quests v3.15-b636bef (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.tasktype.TaskTypeManager.getTaskTypes()" because the return value of "com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.getTaskTypeManager()" is null
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onDisable(BukkitQuestsPlugin.java:507) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:510) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:435) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:403) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:734) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Steps to Reproduce

To encounter this error, simply start Quests with version 3.15-b636bef using Imanity Spigot or any server startup software that supports Java 17.

### Environment

- Minecraft version: 1.8
- Server software: Imanity - Software
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
try latest build (already fixed)

**Comment by Krakenied** [comment]
@ArifErdoganK has using the latest build solved the issue?

**Comment by nonamegizli** [comment]
> ### Description of Bug
> `[01:01:33] [INFO]: [Quests] Enabling Quests v3.15-b636bef [01:01:33] [INFO]: [Quests] Running server scheduler: BukkitServerSchedulerAdapter [01:01:33] [INFO]: [Quests] Initialising storage provider 'mysql' [01:01:33] [INFO]: [Quests] Automatically upgrading database schema from version 1 to 2 [01:01:33] [INFO]: [Quests] Your server is running version 1.8 [01:01:33] [ERROR]: Error occurred while enabling Quests v3.15-b636bef (Is it up to date?) java.lang.NoClassDefFoundError: org/bukkit/boss/BarColor at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:679) ~[?:?] at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:510) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:435) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:403) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:734) ~[spigot.jar:git-iSpigot-PaperEdition] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.lang.ClassNotFoundException: org.bukkit.boss.BarColor at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-iSpigot-PaperEdition] at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] ... 13 more [01:01:33] [INFO]: [Quests] Disabling Quests v3.15-b636bef [01:01:33] [ERROR]: Error occurred while disabling Quests v3.15-b636bef (Is it up to date?) java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.tasktype.TaskTypeManager.getTaskTypes()" because the return value of "com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.getTaskTypeManager()" is null at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onDisable(BukkitQuestsPlugin.java:507) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:510) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:435) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:403) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389) ~[spigot.jar:git-iSpigot-PaperEdition] at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:734) ~[spigot.jar:git-iSpigot-PaperEdition] at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> ### Steps to Reproduce
> To encounter this error, simply start Quests with version 3.15-b636bef using Imanity Spigot or any server startup software that supports Java 17.
> 
> ### Environment
> * Minecraft version: 1.8
> * Server software: Imanity - Software
> * Quests version: 3.15-b636bef
> 
> ### Agreements
> * [x]  I am running the latest version of Quests
> * [x]  I am certain this issue is unique and a similar issue is not currently open
> * [x]  I am using a version of Minecraft which is supported by Quests
> 
> ### Other
> _No response_

sen yapamamışsın ağlama boş yere

**Comment by ArifErdoganK** [comment]
> @ArifErdoganK has using the latest build solved the issue?

It seems like files need to be regenerated in order to successfully transition from the old version to the new version.
