### ISSUE TITLE
Could not set color for the initialized boss bar implementation on startup

### ISSUE THREAD

**Issue by Strahilchu** [LMBishop/Quests#643]
### Description of Bug

[Quests] Enabling Quests v3.15-b636bef
[20:23:29 INFO]: [Quests] Running server scheduler: FoliaServerScheduler
[20:23:29 ERROR]: [Quests] Could not set color for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: color section is missing
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[20:23:29 ERROR]: [Quests] Could not set style for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: style section is missing
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Steps to Reproduce

Unknown

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Currently there is no auto update. However I have a local experimental branch and I'm working on introducing such a feature.

**Comment by Strahilchu** [comment]
I have a custom config from a while ago because I bought 1300 pre-made quests for the plugin so that's why I had to carefully implement the changes to make sure I didn't break everything
