### ISSUE TITLE
Quest Can't execute give command when full?

### ISSUE THREAD

**Issue by Speedspencer** [LMBishop/Quests#653]
### Description of Bug

```
[15:11:05 WARN]: [Quests] Global task for Quests v3.15-b636bef generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'craftorithm' in plugin Craftorithm v1.9.3-20240411
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at com.leonardobishop.quests.bukkit.questcontroller.NormalQuestController.lambda$completeQuestForPlayer$0(NormalQuestController.java:237) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.scheduler.folia.FoliaServerScheduler.lambda$runTask$0(FoliaServerScheduler.java:59) ~[Quests-3.15-b636bef.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException
```

### Steps to Reproduce

Use craftorithm 
Save some items in there
fill your inventory with any items
complete quest with that quest giving the item

### Environment

- Minecraft version: This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)
- Server software: Folia
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

https://www.spigotmc.org/resources/%E2%9C%A8craftorithm-1-13-1-20-4-%E2%9A%99%EF%B8%8Fcustomize-your-crafting-system%E2%9A%99%EF%B8%8F-%E2%9A%A1folia-support%E2%9A%A1.108429/

**Comment by Speedspencer** [comment]
Doesn't seems to be problem with quest.
