### ISSUE TITLE
disabled on startup

### ISSUE THREAD

**Issue by espen96** [LMBishop/Quests#66]
**Description of Error**
disabled on startup

**Server:**
 - Minecraft Version: 1.15.1
 - Mod Name: Paper

**Plugin:**
 - Version: 2.6.4

**Stacktrace**
`[11:15:05] [Server thread/ERROR]: Error occurred while enabling Quests v2.6.4 (Is it up to date?)
java.lang.NullPointerException: null
	at com.leonardobishop.quests.Quests.onEnable(Quests.java:123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-50]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-50]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-50]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[11:15:05] [Server thread/INFO]: [Quests] Disabling Quests v2.6.4`

**Comment by nicuch** [comment]
Editing plugin.yml inside the jar, its sounds familiar?
You probably removed the command "quests" from that file.

**Comment by espen96** [comment]
Haven't touched the jar at all, I'll take a closer look at my plug-ins to see if any plug-in could have messed with the loading somehow

**Comment by espen96** [comment]
Ok, seems it was a plug-in that did it Adjusted a few things that could have been responsible. Not sure exactly what it was, but everything appears to be fine now
