### ISSUE TITLE
Error in console last dev build

### ISSUE THREAD

**Issue by NevileeV** [LMBishop/Quests#660]
### Description of Bug

[19:26:32 ERROR]: [Quests] Could not set color for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: color section is missing
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:702) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:317) ~[Quests-3.15-032f4bb.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2183]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:26:32 ERROR]: [Quests] Could not set style for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: style section is missing
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:702) ~[Quests-3.15-032f4bb.jar:?]
        at Quests-3.15-032f4bb.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:317) ~[Quests-3.15-032f4bb.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2183]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2183]

### Steps to Reproduce

start server purpur = errors in console

### Environment

- Minecraft version: 1.20.6
- Server software: 1.20.6 purpur last build
- Quests version: last deb build Quests-3.15-032f4bb.

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
`I am certain this issue is unique and a similar issue is not currently open`
try again lol
