### ISSUE TITLE
Not working in 1.20.6

### ISSUE THREAD

**Issue by BurkenDev** [LMBishop/Quests#670]
### Description of Bug

Not working in 1.20.6

[19:21:30] [Server thread/INFO]: [Quests] Loading server plugin Quests v3.15-b636bef
[19:21:30] [Server thread/INFO]: [Quests] Enabling Quests v3.15-b636bef
[19:21:30] [Server thread/INFO]: [Quests] Running server scheduler: FoliaServerScheduler
[19:21:30] [Server thread/INFO]: [Quests] Initialising storage provider 'yaml'
[19:21:30] [Server thread/INFO]: [Quests] Your server is running version 1.20
[19:21:30] [Server thread/ERROR]: [Quests] Could not set color for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: color section is missing
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[pluginmanager-2.7.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:784) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:770) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:21:30] [Server thread/ERROR]: [Quests] Could not set style for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: style section is missing
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[pluginmanager-2.7.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:784) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:770) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:21:30] [Server thread/ERROR]: Error occurred while enabling Quests v3.15-b636bef (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setItemGetter(BukkitQuestsPlugin.java:709) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:314) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[pluginmanager-2.7.1.jar:?]
        at pluginmanager-2.7.1.jar/net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[pluginmanager-2.7.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:784) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:770) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.util.CompatUtils.<clinit>(CompatUtils.java:8) ~[Quests-3.15-b636bef.jar:?]
        ... 41 more
[19:21:30] [Server thread/INFO]: [Quests] Disabling Quests v3.15-b636bef
[19:21:30] [Server thread/ERROR]: Error occurred while disabling Quests v3.15-b636bef
java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.tasktype.TaskTypeManager.getTaskTypes()" because the return value of "com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.getTaskTypeManager()" is null
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onDisable(BukkitQuestsPlugin.java:507) ~[Quests-3.15-b636bef.jar:?]

### Steps to Reproduce

Start in 1.20.6

### Environment

- Minecraft version: 1.20.6
- Server software: Paper
- Quests version: Quests-3.15-b636be (latest on spigot as of today)

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Spigot page states compatability with 1.20.* which doesn't seem is the case. Please fix asap thanks :)

**Comment by Krakenied** [comment]
Its supported in latest dev build

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/actions/runs/9261409593
