### ISSUE TITLE
1.20.4 ERROR

### ISSUE THREAD

**Issue by kurkinsnetwork** [LMBishop/Quests#672]
### Description of Bug

[00:41:07 ERROR]: [Quests] Could not set color for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: color section is missing
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[00:41:07 ERROR]: [Quests] Could not set style for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: style section is missing
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Steps to Reproduce

ERROR

### Environment

- Minecraft version: 1.20.4
- Server software: PAPER
- Quests version:3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Your config just is not up to date (it can be safely ignored). Also I recommend using https://github.com/LMBishop/Quests/actions/runs/9320043543 - it has some improvements and fixed added after 3.15 release. It will also tell you where to look for updated config
