### ISSUE TITLE
1.20.6 Plugin not working error

### ISSUE THREAD

**Issue by t4ba** [LMBishop/Quests#679]
### Description of Bug

[07:43:42 ERROR]: Error occurred while enabling Quests v3.15-b636bef (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setItemGetter(BukkitQuestsPlugin.java:709) ~[Quests-3.15-b636bef.jar:?]
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:314) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.util.CompatUtils.<clinit>(CompatUtils.java:8) ~[Quests-3.15-b636bef.jar:?]
        ... 14 more

[07:43:42 INFO]: [Quests] Disabling Quests v3.15-b636bef
[07:43:42 ERROR]: Error occurred while disabling Quests v3.15-b636bef
java.lang.NullPointerException: Cannot invoke "com.leonardobishop.quests.common.tasktype.TaskTypeManager.getTaskTypes()" because the return value of "com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.getTaskTypeManager()" is null
        at Quests-3.15-b636bef.jar/com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onDisable(BukkitQuestsPlugin.java:507) ~[Quests-3.15-b636bef.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2226-86ad0b3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to Reproduce

run the plugin on 1.20.6 version

### Environment

- Minecraft version: 1.20.6
- Server software: Purpur 
- Quests version: 3.15

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [ ] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
It's supported in dev builds
https://github.com/LMBishop/Quests/actions/runs/9519979769

**Comment by t4ba** [comment]
thanks !
