### ISSUE TITLE
Could not set color for initialized boss bar implementation

### ISSUE THREAD

**Issue by imstuart** [LMBishop/Quests#691]
### Description of Bug

```yml
[11:49:13] [Server thread/ERROR]: [Quests] Could not set color for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: color section is missing
	at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:37) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:49:13] [Server thread/ERROR]: [Quests] Could not set style for the initialized boss bar implementation, using default instead!
java.lang.IllegalStateException: style section is missing
	at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.loadConfig(BossBar_Bukkit.java:96) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.hook.bossbar.BossBar_Bukkit.<init>(BossBar_Bukkit.java:40) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.setBossBarHandle(BukkitQuestsPlugin.java:680) ~[Quests-3.15-b636bef.jar:?]
	at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:308) ~[Quests-3.15-b636bef.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:49:13] [Server thread/INFO]: [Quests] Metrics started. This can be disabled at /plugins/bStats/config.yml.
```

### Steps to Reproduce

Run the server 

### Environment

- Minecraft version: 1.20.2
- Server software: Debian 12 Java 21
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Update your config
