### ISSUE TITLE
 NPCInteractEvent

### ISSUE THREAD

**Issue by tumasov69** [LMBishop/Quests#693]
### Description of Bug

Conflicts with ServerNPC

[22:36:22 ERROR]: Could not pass event NPCInteractEvent to Quests v3.15-b636bef
java.lang.NoSuchMethodError: 'java.lang.String com.isnakebuzz.npcapi.entities.SnakeNPC.getName()'
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.ServerNPCInteractTaskType.onNPCInteract(ServerNPCInteractTaskType.java:43) ~[Quests-3.15-b636bef.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1337.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.isnakebuzz.servernpc.nms.v1_20_R3.task.TaskCallClickEvent.run(TaskCallClickEvent.java:33) ~[ServerNPC-1.17.2-RELEASE-b1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to Reproduce

After clicking on the NPC and opening the menu, it spams with errors

### Environment

- Minecraft version:
- Server software:
- Quests version:

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
is your servernpc up to date?

**Comment by tumasov69** [comment]
> is your servernpc up to date?

I am using the latest version ServerNPC-1.17.2-RELEASE-b1

**Comment by Krakenied** [comment]
Could you try with dev build? https://github.com/LMBishop/Quests/actions/runs/9906616379

I haven't fixed it, however maybe it had been fixed before

**Comment by Krakenied** [comment]
If you need to use Java 17, then add `--add-opens=java.base/java.text=ALL-UNNAMED` just after `java` in your start script

**Comment by tumasov69** [comment]
I did everything as I was told, it helped, thank you

**Comment by Krakenied** [comment]
Close the issue if it works
