### ISSUE TITLE
While creating/updating quest sometimes plugin deleting all quest files

### ISSUE THREAD

**Issue by xKefir** [LMBishop/Quests#696]
### Description of Bug

I have that issue 2nd time.

### Steps to Reproduce

[22:03:52 WARN]: java.nio.file.AccessDeniedException: plugins/Quests/quests/p4-1.yml[22:03:52 WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)[22:03:52 WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)[22:03:52 WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)[22:03:52 WARN]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)[22:03:52 WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)[22:03:52 WARN]: 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.Files.readAttributes(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.FileTreeWalker.getAttributes(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.FileTreeWalker.next(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)[22:03:52 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.config.BukkitQuestsLoader.loadQuests(BukkitQuestsLoader.java:406)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.reloadQuests(BukkitQuestsPlugin.java:537)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.command.AdminReloadCommandHandler.handle(AdminReloadCommandHandler.java:24)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.command.CommandSwitcher.handle(CommandSwitcher.java:29)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.command.CommandSwitcher.handle(CommandSwitcher.java:29)[22:03:52 WARN]: 	at Quests-3.15-b636bef (2).jar//com.leonardobishop.quests.bukkit.command.QuestsCommandSwitcher.onCommand(QuestsCommandSwitcher.java:69)[22:03:52 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)[22:03:52 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)[22:03:52 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)[22:03:52 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)[22:03:52 WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)[22:03:52 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)[22:03:52 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)[22:03:52 WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)[22:03:52 WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)[22:03:52 WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)[22:03:52 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)[22:03:52 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)[22:03:52 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)[22:03:52 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)[22:03:52 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)[22:03:52 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)[22:03:52 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)[22:03:52 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)[22:03:52 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)[22:03:52 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)[22:03:52 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)[22:03:52 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)[22:03:52 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)[22:03:52 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

### Environment

- Minecraft version: 1.20.4
- Server software: System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.11+9) Host: Linux 5.18.4-051804-generic (amd64)
- Quests version: Quests-3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Seems to be an issue more on the hardware side lol
