### ISSUE TITLE
CoreProtect concurrency issue (ConcurrentModificationException)

### ISSUE THREAD

**Issue by DarkyG2** [LMBishop/Quests#707]
### Description of Bug

I'm getting this random error with quests that has a coreprotect hook to it:
```
[18:56:40 WARN]: java.util.ConcurrentModificationException
[18:56:40 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[18:56:40 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[18:56:40 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.api.QueueLookup.performLookup(QueueLookup.java:55)
[18:56:40 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.CoreProtectAPI.queueLookup(CoreProtectAPI.java:182)
[18:56:40 WARN]:        at Quests-3.15-2869ab1.jar//com.leonardobishop.quests.bukkit.hook.coreprotect.CoreProtectHook.lambda$checkBlock$3(CoreProtectHook.java:25)
[18:56:40 WARN]:        at Quests-3.15-2869ab1.jar//com.leonardobishop.quests.bukkit.scheduler.folia.FoliaServerScheduler.lambda$runTaskAsynchronously$1(FoliaServerScheduler.java:64)
[18:56:40 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[18:56:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[18:56:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[18:56:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps to Reproduce

1. Have multiple people do quests that has this option of coreprotect
2. have dozens of players online
3. boom random error

### Environment

- Minecraft version: 1.20.4
- Server software: Folia
- Quests version: 3.15-2869ab1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Task example:
```YAML
  1:
    type: "blockbreak"
    amount: 448
    block:
      - "BLACKSTONE"
    check-coreprotect: true
    check-coreprotect-time: 1800
```

**Comment by Krakenied** [comment]
It's CoreProtect issue, dupe of https://github.com/LMBishop/Quests/issues/664

**Comment by Krakenied** [comment]
While using BlockTracker for it is still the recommended approach, it seems to be finally fixed https://github.com/PlayPro/CoreProtect/issues/481#event-24847833640
