### ISSUE TITLE
PlaceholderAPI console error

### ISSUE THREAD

**Issue by PirataGu** [LMBishop/Quests#738]
### Description of Bug

[11:53:43 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-quests.jar (is a dependency missing?)
java.lang.NoClassDefFoundError: me/pikamug/quests/quests/Quest
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:429) ~[PlaceholderAPI-2.11.6(2).jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.pikamug.quests.quests.Quest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more

### Steps to Reproduce

Just start the server...

### Environment

- Minecraft version: 1.20.4
- Server software: git-Purpur-2176 (MC: 1.20.4)
- Quests version: 3.15.2-b216e2b

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Please read the warning https://quests.leonardobishop.com/tools/placeholderapi.html
