### ISSUE TITLE
Plugin initialization error on startup 1.16.5(JAVA 17)

### ISSUE THREAD

**Issue by azzztec** [LMBishop/Quests#756]
### Description of Bug

![image](https://github.com/user-attachments/assets/63b1247d-a9d2-4f6b-9f3d-5a3d691789de)

When using /quests
![image](https://github.com/user-attachments/assets/2b77abfe-693f-4bbf-add7-4bdb75afa909)

### Steps to Reproduce

Start server

### Environment

**Java Version**
java 17.0.6 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

**Minecraft Version**
purpur-1.17.1-1428.jar

**Quests Version**
Quests-3.15.2-b216e2b-downgraded-17-shaded

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
Probably it's Purpur 1.17.1 issue - works properly on Paper 1.17.1

**Comment by Krakenied** [comment]
```
[20:41:15 WARN]: [Quests] Task #4 for Quests v3.15.2-b216e2b generated an exception
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
        at com.leonardobishop.quests.bukkit.util.chat.MiniMessageParser.<init>(MiniMessageParser.java:13) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.util.chat.Chat.<clinit>(Chat.java:49) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.hook.itemgetter.ItemGetter14.getItem(ItemGetter14.java:71) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.getConfiguredItemStack(BukkitQuestsPlugin.java:656) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.config.BukkitQuestsLoader.loadQuests(BukkitQuestsLoader.java:123) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.reloadQuests(BukkitQuestsPlugin.java:632) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at com.leonardobishop.quests.bukkit.BukkitQuestsPlugin.lambda$onEnable$81(BukkitQuestsPlugin.java:528) ~[Quests-3.15.2-b216e2b-downgraded-17-shaded.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:1575) ~[?:?]

**Comment by Krakenied** [comment]
Fixed in this build https://github.com/Krakenied/Quests/actions/runs/12508026064/artifacts/2364193185

**Comment by azzztec** [comment]
@Krakenied its ok on startup but still doest work when using **/quests**
![image](https://github.com/user-attachments/assets/3b9562a3-91d2-4059-bd72-bb562ac2ebeb)

**Comment by Krakenied** [comment]
I think that I managed to fix it, here is the JAR
https://github.com/Krakenied/Quests/actions/runs/12546162784

**Comment by azzztec** [comment]
@Krakenied 
![image](https://github.com/user-attachments/assets/6e58b894-f647-420b-9743-e7e69311803d)

**Comment by Krakenied** [comment]
Add `--add-opens=java.base/java.text=ALL-UNNAMED` to your startup command - it's required due to the downgrade

**Comment by azzztec** [comment]
@Krakenied 
works, spasibo!
