### ISSUE TITLE
Could not pass inventory event + issue with other gui from other plugins

### ISSUE THREAD

**Issue by Tikifirst** [LMBishop/Quests#89]
**Description of Error**

First error : when I want to cancel a quest, an InventoryClickEvent is triggered : 

`[02:17:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Quests v2.9.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: RED_STAINED_GLASS_PANE
	at com.leonardobishop.quests.obj.misc.QMenuCancel.toInventory(QMenuCancel.java:55) ~[?:?]
	at com.leonardobishop.quests.events.EventInventory.onEvent(EventInventory.java:93) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 16 more`

That's, I think, because I am under spigot 1.8, in which RED_STAINED_GLASS_PANE does not exist, only STAINED_GLASS_PANE and the data 14 ^^

Second issue : with ALL guis from other plugins (deluxe menu, backpacks, ...) when I click anything, that makes me accept a quest relative to the item I've clicked on, like the plugin does not recognize the gui is not a quest gui :/

**To Reproduce**

First issue : try cancel a quest under spigot 1.8
Second issue : try clicking anything on a gui from other plugin (chestcommands, deluxemenu, ...)

**Screenshots**
no screen needed

**Server (please complete the following information):**
 - Minecraft Version: 1.8
 - Mod Name: PaperSpigot 1.8

**Plugin (please complete the following information):**
 - Version: Latest one : from 19 April "Fix Null Erro" on uptades on spigot

**Comment by LMBishop** [comment]
the second issue there would likely be caused by the first one, as quests thinks a menu is open but an in reality error occured when opening it
